import Head from 'next/head'
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from 'next/image';
import deved from '../public/Razin.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from "../public/web1.png";
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Muhammad Razin Syakib Portofolo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-10 dark:bg-gray-900'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>razinsyakib.</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl' />
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10 py-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Muhammad Razin Syakib</h2>
            <h3 className='text-2xl py-2'>Web Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id aut dolores aliquid eaque consequatur doloribus.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20'>
            <Image src={deved} layout='fill' objectFit='cover' />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I Offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident error doloribus quod velit harum
              <span className='text-teal-500'> lorem</span> Lorem ipsum dolor sit <span className='text-teal-500'> ipsum</span> Lorem ipsum dolor sit amet.</p>
            <p className='text-md py-2 leading-8 text-gray-800'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident error doloribus quod velit harum
              <span className='text-teal-500'> lorem</span> Lorem ipsum dolor sit <span className='text-teal-500'> ipsum</span> Lorem ipsum dolor sit amet.</p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl'>
              <Image src={design} width={100} height={100} className='mx-auto' />
              <h3>UI/UX Designs</h3>
              <p className='py-2'>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
              <h4 className='py-4 text-teal-600'>Tools I use: </h4>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Adobe XD</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl'>
              <Image src={code} width={100} height={100} className='mx-auto' />
              <h3>UI/UX Designs</h3>
              <p className='py-2'>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
              <h4 className='py-4 text-teal-600'>Tools I use: </h4>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Adobe XD</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl'>
              <Image src={consulting} width={100} height={100} className='mx-auto' />
              <h3>UI/UX Designs</h3>
              <p className='py-2'>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
              <h4 className='py-4 text-teal-600'>Tools I use: </h4>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Adobe XD</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Portofolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident error doloribus quod velit harum
              <span className='text-teal-500'> lorem</span> Lorem ipsum dolor sit <span className='text-teal-500'> ipsum</span> Lorem ipsum dolor sit amet.</p>
            <p className='text-md py-2 leading-8 text-gray-800'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident error doloribus quod velit harum
              <span className='text-teal-500'> lorem</span> Lorem ipsum dolor sit <span className='text-teal-500'> ipsum</span> Lorem ipsum dolor sit amet.</p>
          </div>
          <div className='flex flex-col gap-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'><Image src={web1} className='rounded-lg object-cover width={"100%"} height={"100%"} layout="responsive"' /></div>
            <div className='basis-1/3 flex-1'><Image src={web1} className='rounded-lg object-cover width={"100%"} height={"100%"} layout="responsive"' /></div>
            <div className='basis-1/3 flex-1'><Image src={web1} className='rounded-lg object-cover width={"100%"} height={"100%"} layout="responsive"' /></div>
            <div className='basis-1/3 flex-1'><Image src={web1} className='rounded-lg object-cover width={"100%"} height={"100%"} layout="responsive"' /></div>
            <div className='basis-1/3 flex-1'><Image src={web1} className='rounded-lg object-cover width={"100%"} height={"100%"} layout="responsive"' /></div>
            <div className='basis-1/3 flex-1'><Image src={web1} className='rounded-lg object-cover width={"100%"} height={"100%"} layout="responsive"' /></div>
          </div>
        </section>
      </main>
    </div>
  )
}
